### ISSUE TITLE
HTTPS redirects to HTTP

### ISSUE THREAD

**Issue by drojf** [07th-mod/website#3]
Currently, [**https**://07th-mod.com/](https://07th-mod.com/) redirects to  **http**://07th-mod.com/

https://www.07th-mod.com/ also redirects to the http version of the website

However, https://www.07th-mod.com/home/ works properly

I'm guessing the redirect rules always go to the **http** version no matter what, if you land on a page which redirects. It should probably always go to the **https** version

**Comment by ItaloKnox** [comment]
I'm looking into this. I just need to remember how I set up the redirection.

Edit: Oh, ok, so it's a redirection script in our home. Script seems to be working as intended, so I'm looking for a better solution.

**Comment by drojf** [comment]
seems to work now :)
