### ISSUE TITLE
Add redirect if users attempt to access old Umineko Project downloads

### ISSUE THREAD

**Issue by drojf** [07th-mod/website#4]
Currently [the Umineko Project downloads page](https://umineko-project.org/en/downloads/
) still links our downloads. But since we no longer host any downloads on 07th-mod.com, the links redirect to our homepage, and users often go to our discord asking about it or reporting this problem.

I think it would be too difficult to get the links removed at this point.

But on our side, we could redirect any accesses to `https://07th-mod.com/Aurora/*` to a special landing page with an explanation that we don't host the files (or, if someone else ends up mirroring the files, we could link to them instead). 

The links on that page all start with `https://07th-mod.com/Aurora`, but to be exact, these are the URLS:

```
https://07th-mod.com/Aurora/umiproj_31.12.19.7z.001
https://07th-mod.com/Aurora/umiproj_31.12.19.7z.002
https://07th-mod.com/Aurora/umiproj_31.12.19.7z.003
https://07th-mod.com/Aurora/umiproj_31.12.19.7z.004
https://07th-mod.com/Aurora/umiproj_31.12.19.7z.005
https://07th-mod.com/Aurora/umiproj_31.12.19.7z.006
https://07th-mod.com/Aurora/umiproj_31.12.19.7z.007
https://07th-mod.com/Aurora/umiproj_31.12.19.7z.008
https://07th-mod.com/Aurora/umiproj_31.12.19.7z.009
https://07th-mod.com/Aurora/umiproj_31.12.19.7z.010
https://07th-mod.com/Aurora/umiproj_31.12.19.7z.011
https://07th-mod.com/Aurora/umiproj_31.12.19.7z.012
```

@ItaloKnox If you can create a redirect to a dummy page on our website (or on the wiki), I'll fill in the page for you. I just need the redirect created.

I'm not really sure how to do it, but something like this maybe?
```
RedirectMatch 301 ^/Aurora/umiproj https://wiki.07th-mod.com/umineko-project-no-longer-mirrored/
```

Then I can make the https://wiki.07th-mod.com/umineko-project-no-longer-mirrored/ page later.

**Comment by drojf** [comment]
@andOlga has implemented a redirect on the index.html page, so modifying .htaccess etc. is no longer required. I just need to write up the redirect page. See

https://github.com/07th-mod/website/commit/769f8471b362aa0a986f7942094909dfffcea1c6
https://github.com/07th-mod/website/commit/b21b5ceb775084ba8a154c37ff2a97529ac901f0
https://github.com/07th-mod/website/commit/83246f2ad96f6743743e1b6b738b0009e34a7092

----

Also, I thought about it and  I think the wiki idea I propsed is a bad idea, as it might make users think it redirected wrong.

I'll try to make a simple "something went wrong" looking page with minimal content so it's obvious what to read.

**Comment by drojf** [comment]
OK, I've filled in the "downloads no longer available page" here: https://07th-mod.com/umineko-project-no-longer-supported/

Feel free to edit it if something seems wrong.

**Comment by ItaloKnox** [comment]
I can't believe my Thunderbird was filtering all GH notifications. Just found out because somehow this last one got through my phone. I can do redirects at DNS level if you think that's a cleaner solution, though the current one should work fine unless we change something (I think it's unlikely).

Next time I seem MIA just ping me on Discord and I'll fix it. 😞

**Comment by drojf** [comment]
ah yea, I'll ping you on discord next time....I guess when I made the issue, it wasn't super urgent so I didn't want to ping you until after some time had passed...but then I just didn't follow it up later.

I agree, the current method is working so I'd just leave it
